### ISSUE TITLE
Any further roadmaps?

### ISSUE THREAD

**Issue by BraINstinct0** [znone/Win32DiskImager#1]
Since the original Win32DiskImager seems to not work on many, many cases, I thought I'd fork it and gradually improve it. But here is an already-seemingly working fork of it, so I think it'd be better to just commit here. Any plans?

**Comment by znone** [comment]
You can fork from my project and realize your idea.I have no need to update it for the time being. If you have any pull request, I will consider merging it.

**Comment by BraINstinct0** [comment]
If I happen to put my hands on the code I'll simply fork this and release. Thanks!
Will close as solved
